version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt update clean assembly
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - project/target
      - run: cp target/slack-ojichat.jar ops/slack-ojichat.jar
      - persist_to_workspace:
          root: .
          paths:
            - ops
  heroku_deploy:
    # https://devcenter.heroku.com/articles/container-registry-and-runtime
    environment:
      HEROKU_APP_NAME: slack-ojichat
      # HEROKU_API_KEY: "in deploy(circleci) setting"
      # SLACK_TOKEN: "in running(heroku) setting"
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache
      - run:
          name: heroku init
          command: |
            sudo npm install -g heroku
            heroku maintenance:on --app ${HEROKU_APP_NAME}
            docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .

      - run:
          name: docker build
          command: docker build -t ${HEROKU_APP_NAME}:${CIRCLE_SHA1} ops
      - run:
          name: heroku push
          command: |
            docker push registry.heroku.com/${HEROKU_APP_NAME}/worker
            heroku container:push worker --app ${HEROKU_APP_NAME}
            heroku container:release worker --app ${HEROKU_APP_NAME}

      - run: heroku maintenance:off --app ${HEROKU_APP_NAME}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - heroku_deploy:
          requires:
            - build
          filters:
            branches:
              only: master
