version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt update clean scalafmt test assembly
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - project/target
      - persist_to_workspace:
          root: .
          paths:
            - ops
  heroku_deploy:
    # https://devcenter.heroku.com/articles/container-registry-and-runtime
    environment:
      # DOCKER_BUILDKIT: 1 未対応
      # HEROKU_APP_NAME: "in deploy(circleci) setting"
      # HEROKU_API_KEY: "in deploy(circleci) setting"
      # SLACK_TOKEN: "in running(heroku) setting"
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: heroku init
          command: |
            npm install
            echo ${HEROKU_API_KEY} | docker login --username=_ --password-stdin registry.heroku.com
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
      - setup_remote_docker
      - attach_workspace:
          at: .

      - run:
          name: docker build
          command: |
            docker build \
              --build-arg HEROKU_APP_NAME="${HEROKU_APP_NAME}" \
              --build-arg SLACK_TOKEN="${SLACK_TOKEN}" \
              -t registry.heroku.com/${HEROKU_APP_NAME}/worker ops
      - run:
          name: heroku push
          command: docker push registry.heroku.com/${HEROKU_APP_NAME}/worker
      - run:
          name: heroku release
          command: |
            ./node_modules/.bin/heroku maintenance:on --app ${HEROKU_APP_NAME}
            ./node_modules/.bin/heroku container:release worker --app ${HEROKU_APP_NAME}
            ./node_modules/.bin/heroku maintenance:off --app ${HEROKU_APP_NAME}
  ojisan_ohayou:
    environment:
      # HEROKU_APP_NAME: "in deploy(circleci) setting"
      # HEROKU_API_KEY: "in deploy(circleci) setting"
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
      - run: ./node_modules/.bin/heroku ps:scale worker=1 -a ${HEROKU_APP_NAME}
  ojisan_oyasumi:
    environment:
      # HEROKU_APP_NAME: "in deploy(circleci) setting"
      # HEROKU_API_KEY: "in deploy(circleci) setting"
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
      - run: ./node_modules/.bin/heroku ps:scale worker=0 -a ${HEROKU_APP_NAME}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - heroku_deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  asa:
    triggers:
      - schedule:
          # オジサンは朝早い(0600)
          cron: "0 21 * * *" # JST=UTC+0900
          filters:
            branches:
              only:
                - /.*/
    jobs:
      - ojisan_ohayou
  yoru:
    triggers:
      - schedule:
          # オジサンは夜早い(2100)
          cron: "0 12 * * *" # JST=UTC+0900
          filters:
            branches:
              only:
                - /.*/
    jobs:
      - ojisan_oyasumi
