version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt update clean assembly
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - project/target
      - persist_to_workspace:
          root: .
          paths:
            - ops
  heroku_deploy:
    # https://devcenter.heroku.com/articles/container-registry-and-runtime
    environment:
      # HEROKU_APP_NAME: "in deploy(circleci) setting"
      # HEROKU_API_KEY: "in deploy(circleci) setting"
      # SLACK_TOKEN: "in running(heroku) setting"
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache
      - run:
          name: heroku init
          command: |
            sudo npm install -g heroku
            echo ${HEROKU_API_KEY} | docker login --username=_ --password-stdin registry.heroku.com
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
            - /usr/local/lib/node_modules
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .

      - run:
          name: docker build
          command: docker build -t registry.heroku.com/${HEROKU_APP_NAME}/worker ops
      - run:
          name: heroku push
          command: docker push registry.heroku.com/${HEROKU_APP_NAME}/worker
      - run:
          name: heroku release
          command: |
            heroku maintenance:on --app ${HEROKU_APP_NAME}
            heroku container:release worker --app ${HEROKU_APP_NAME}
            heroku maintenance:off --app ${HEROKU_APP_NAME}
  ojisan_ohayou:
    environment:
      # HEROKU_APP_NAME: "in deploy(circleci) setting"
      # HEROKU_API_KEY: "in deploy(circleci) setting"
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache
      - run: sudo npm install -g heroku
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
            - /usr/local/lib/node_modules
      - run: heroku ps:restart worker -a ${HEROKU_APP_NAME}
  ojisan_oyasumi:
    environment:
      # HEROKU_APP_NAME: "in deploy(circleci) setting"
      # HEROKU_API_KEY: "in deploy(circleci) setting"
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache
      - run: sudo npm install -g heroku
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
            - /usr/local/lib/node_modules
      - run: heroku ps:stop worker -a ${HEROKU_APP_NAME}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - heroku_deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  asa:
    triggers:
      - schedule:
          # オジサンは朝早い(0600)
          cron: "0 21 * * *" # JST=UTC+0900
          filters:
            branches:
              only:
                - /.*/
    jobs:
      - ojisan_ohayou
  yoru:
    triggers:
      - schedule:
          # オジサンは夜早い(2100)
          cron: "0 12 * * *" # JST=UTC+0900
          filters:
            branches:
              only:
                - /.*/
    jobs:
      - ojisan_oyasumi
